apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-simple
  namespace: smart-mechanical-workshop
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: mysql-client
        image: mysql:8.0
        command: ["bash"]
        args:
        - -c
        - |
          set -e

          DB_HOST_CLEAN=$(echo $DB_HOST | cut -d':' -f1)
          echo "🔗 Conectando ao RDS: $DB_HOST_CLEAN"

          echo "⏳ Aguardando RDS ficar disponível..."
          until mysql -h $DB_HOST_CLEAN -P 3306 -u $DB_USER -p$DB_PASSWORD -e "SELECT 1;" > /dev/null 2>&1; do
            echo "RDS não está pronto ainda. Aguardando 5 segundos..."
            sleep 5
          done

          echo "✅ RDS disponível! Executando inicialização..."
          mysql -h $DB_HOST_CLEAN -P 3306 -u $DB_USER -p$DB_PASSWORD < /scripts/init.sql

          echo "📊 Populando dados de exemplo..."
          mysql -h $DB_HOST_CLEAN -P 3306 -u $DB_USER -p$DB_PASSWORD < /scripts/data.sql

          echo "🎉 Inicialização do banco concluída com sucesso!"

          echo "📋 Verificando tabelas criadas..."
          mysql -h $DB_HOST_CLEAN -P 3306 -u $DB_USER -p$DB_PASSWORD -e "USE workshopdb; SHOW TABLES;"

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smart-mechanical-workshop-secrets
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: init-scripts
        configMap:
          name: db-init-scripts-simple
  backoffLimit: 3
