apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# AWS-specific resources
resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- ../../base/secrets.yaml
- ../../base/api-deployment.yaml
- ../../base/services.yaml
- ../../base/mailhog-deployment.yaml
- db-init-simple.yaml
- db-init-job-simple.yaml

# AWS-specific patches
patches:
- path: services-loadbalancer.yaml
- path: configmap-aws.yaml
- path: api-deployment-aws.yaml

# Namespace for AWS deployment
namespace: smart-mechanical-workshop
