apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration
resources:
- ../../base

# AWS-specific overrides
patchesStrategicMerge:
- services-loadbalancer.yaml
- configmap-aws.yaml
- api-deployment-aws.yaml

# Remove MySQL deployment since we use RDS
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: mysql-deployment
  patch: |-
    - op: remove
      path: /

- target:
    group: v1
    version: v1
    kind: Service
    name: mysql-service
  patch: |-
    - op: remove
      path: /

# Namespace for AWS deployment
namespace: smart-mechanical-workshop
