apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-mechanical-workshop-dev

resources:
- ../../base

namePrefix: dev-

labels:
- pairs:
    environment: development

images:
- name: igortessaro/smart-mechanical-workshop-api
  newTag: latest
- name: igortessaro/smart-mechanical-workshop-db
  newTag: latest

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: smart-mechanical-workshop-config
    data:
      ASPNETCORE_ENVIRONMENT: "Development"
      BASE_URL: "http://localhost:5180"
      DB_HOST: "dev-mysql-service"
      DB_PORT: "3306"
      MYSQL_DATABASE: "workshopdb"
      MYSQL_USER: "workshopuser"
      SMTP_HOST: "dev-mailhog-service"
      SMTP_PORT: "1025"
  target:
    kind: ConfigMap
    name: smart-mechanical-workshop-config
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: api-service
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: api-service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: mailhog-service
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: mailhog-service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: mysql-service
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: mysql-service
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-deployment
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: api
            env:
            - name: ConnectionStrings__DefaultConnection
              value: "server=dev-mysql-service;port=3306;database=workshopdb;user=workshopuser;password=workshop123;SslMode=none;AllowPublicKeyRetrieval=True;"
  target:
    kind: Deployment
    name: api-deployment
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mysql-deployment
    spec:
      replicas: 1
  target:
    kind: Deployment
    name: mysql-deployment
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: api-hpa
    spec:
      minReplicas: 1
      maxReplicas: 3
  target:
    kind: HorizontalPodAutoscaler
    name: api-hpa
