apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-mechanical-workshop-prod

resources:
- ../../base
- ingress.yaml

namePrefix: prod-

labels:
- pairs:
    environment: production

images:
- name: igortessaro/smart-mechanical-workshop-api
  newTag: v1.0.0
- name: igortessaro/smart-mechanical-workshop-db
  newTag: v1.0.0

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: smart-mechanical-workshop-config
    data:
      ASPNETCORE_ENVIRONMENT: "Production"
      BASE_URL: "https://api.your-domain.com"
      DB_HOST: "prod-mysql-service"
      DB_PORT: "3306"
      MYSQL_DATABASE: "workshopdb"
      MYSQL_USER: "workshopuser"
      SMTP_HOST: "prod-mailhog-service"
      SMTP_PORT: "1025"
      DEFAULT_CONNECTION_STRING: "server=prod-mysql-service;port=3306;database=workshopdb;user=workshopuser;password=workshop123;SslMode=none;AllowPublicKeyRetrieval=True;"
  target:
    kind: ConfigMap
    name: smart-mechanical-workshop-config
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: api-service
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: api-service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: mailhog-service
    spec:
      type: ClusterIP
  target:
    kind: Service
    name: mailhog-service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: mysql-service
    spec:
      type: ClusterIP
  target:
    kind: Service
    name: mysql-service
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-deployment
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: api
            resources:
              requests:
                memory: "512Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
  target:
    kind: Deployment
    name: api-deployment
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: api-hpa
    spec:
      minReplicas: 3
      maxReplicas: 20
  target:
    kind: HorizontalPodAutoscaler
    name: api-hpa
