apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app.kubernetes.io/name: smart-mechanical-workshop-api
    app.kubernetes.io/component: api
    app.kubernetes.io/version: "latest"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: smart-mechanical-workshop-api
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smart-mechanical-workshop-api
        app.kubernetes.io/component: api
        app.kubernetes.io/version: "latest"
    spec:
      containers:
      - name: api
        image: igortessaro/smart-mechanical-workshop-api:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: DEFAULT_CONNECTION_STRING
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: DB_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smart-mechanical-workshop-secrets
              key: MYSQL_PASSWORD
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: smart-mechanical-workshop-secrets
              key: JWT_KEY
        - name: BaseUrl
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: BASE_URL
        - name: Email__SmtpHost
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: SMTP_HOST
        - name: Email__SmtpPort
          valueFrom:
            configMapKeyRef:
              name: smart-mechanical-workshop-config
              key: SMTP_PORT
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
