apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- pvc.yaml
- mysql-deployment.yaml
- api-deployment.yaml
- mailhog-deployment.yaml
- services.yaml
- hpa.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: smart-mechanical-workshop

images:
- name: igortessaro/smart-mechanical-workshop-api
  newTag: latest
- name: igortessaro/smart-mechanical-workshop-db
  newTag: latest
