name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Format code
      run: dotnet format --verify-no-changes
      env:
        PATH: ${{ runner.tool_cache }}/dotnet:$PATH
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: |
        dotnet test tests/Fiap.Soat.SmartMechanicalWorkshop.Domain.Tests/Fiap.Soat.SmartMechanicalWorkshop.Domain.Tests.csproj
        dotnet test tests/Fiap.Soat.SmartMechanicalWorkshop.Application.Tests/Fiap.Soat.SmartMechanicalWorkshop.Application.Tests.csproj

  integration-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run integration tests
      run: dotnet test tests/Fiap.Soat.SmartMechanicalWorkshop.Integration.Tests/Fiap.Soat.SmartMechanicalWorkshop.Integration.Tests.csproj
