apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-mechanical-workshop-staging

resources:
- ../../base

namePrefix: staging-

labels:
- pairs:
    environment: staging

images:
- name: igortessaro/smart-mechanical-workshop-api
  newTag: staging-latest
- name: igortessaro/smart-mechanical-workshop-db
  newTag: staging-latest

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: smart-mechanical-workshop-config
    data:
      ASPNETCORE_ENVIRONMENT: "Staging"
      BASE_URL: "https://staging-api.your-domain.com"
      DB_HOST: "staging-mysql-service"
      DB_PORT: "3306"
      MYSQL_DATABASE: "workshopdb_staging"
      MYSQL_USER: "workshopuser_staging"
      SMTP_HOST: "staging-mailhog-service"
      SMTP_PORT: "1025"
  target:
    kind: ConfigMap
    name: smart-mechanical-workshop-config
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: api-service
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: api-service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: mailhog-service
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: mailhog-service
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: mysql-service
    spec:
      type: LoadBalancer
  target:
    kind: Service
    name: mysql-service
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-deployment
    spec:
      replicas: 2
  target:
    kind: Deployment
    name: api-deployment
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: api-hpa
    spec:
      minReplicas: 2
      maxReplicas: 5
  target:
    kind: HorizontalPodAutoscaler
    name: api-hpa
